# -*- coding: utf-8 -*-
{
    'name': "Iroom NTMP Connector",
    'summary': "Iroom NTMP Connector",
    'description': """Iroom NTMP Connector""",

    'author': "Ahmed Gaber",
    'category': 'Uncategorized',
    'version': '0.1',
    'depends': ['base', 'hotel', 'hotel_management'],
    'data': [
        'security/ir.model.access.csv',
        'security/groups.xml',
        'data/ntmp.nationality.csv',
        'data/ntmp_visit_purpose.xml',
        'data/ntmp_payment_type.xml',
        'data/ntmp_gender.xml',
        'data/ntmp_customer_type.xml',
        'data/ntmp_room_type.xml',
        'data/ntmp_transaction_type.xml',
        'data/ntmp_rent_type.xml',
        'data/ntmp_expense_type.xml',
        'data/ntmp_cancel_reason.xml',
        'data/ntmp_response_code.xml',
        'views/res_company.xml',
        'views/ntmp_nationality.xml',
        'views/ntmp_visit_purpose.xml',
        'views/ntmp_payment_type.xml',
        'views/ntmp_gender.xml',
        'views/ntmp_customer_type.xml',
        'views/ntmp_room_type.xml',
        'views/ntmp_transaction_type.xml',
        'views/ntmp_rent_type.xml',
        'views/ntmp_expense_type.xml',
        'views/ntmp_cancel_reason.xml',
        'views/ntmp_response_code.xml',
        'views/hotel_room_type.xml',
        'views/hotel_services.xml',
        'views/hotel_reservation.xml',
        'views/hotel_folio.xml',
        'wizards/reservation_cancel.xml'
    ],
}

